name: Build

# TODO: Change trigger to push to master
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - run: gcloud components install beta
      - run: gcloud --version
      - name: Configure Docker
        run: gcloud beta auth configure-docker us-central1-docker.pkg.dev
      - name: Build Docker image
        run: docker image build -t sandbox .
