name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Lint with isort
        run: make lint-isort
      - name: Lint with black
        run: make lint-black
